apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-admin
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-api-admin
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app.kubernetes.io/name: app-api-admin
        version: v0.0.0
        env: dev
    spec:
      # imagePullSecrets:
      #   - name: cjconnect-int-api-admin-server-secret
      containers:
        - name: app-api-admin
          image: "api-admin"
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
            - name: grpc-web
              containerPort: 6565
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/bash", "-c", "jmap -dump:format=b,file=/emptydir/heapdump_before_sigquit.hprof `ps -ef | grep java | grep app.jar | awk '{print$2}'`; \
                sleep 20; \
                kill -3 `ps -ef | grep app.jar | awk '{print $2}'`;sleep 20"]
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /cjconnect/admin/api/monitor/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 150
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /cjconnect/admin/api/monitor/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          resources:
            limits:
              memory: 4Gi
              cpu: "4"
            requests:
              memory: 2Gi
              cpu: "2"
          volumeMounts:
            - name: emptydir-volume
              mountPath: /emptydir
      restartPolicy: Always
      volumes:
      - name: emptydir-volume
        emptyDir: {}